extsoft/dp-151

code-assessment.sh
`code-assessment.sh` will return exit code 11 if there is at least one
error in the procedure, This will encourage Travis to fail.
But if the code assessment is passed, exit code is 0 and build is
passed.
=> Fail Travis build if code assessment is failed

.gitignore, .pylintrc, oct/pages/registration.py, oct/tests/web/registration.py
Modified registration.py files in oct/pages and oct/tests/web.
Functions were implemented for ability running registration test case.
=> Creating registration test case

oct/pages/account.py, oct/pages/login.py, oct/tests/web/login.py
Created login.py module in oct/pages for implementing objects on the Login page.
Created account.py module in oct/pages for implementing objects on the Account page.
Created login.py module in oct/tests/web for implementing and running test case which verifies ability to login into account.
=> Login test case has been created.

oct/pages/brand.py, oct/pages/product_page.py, oct/tests/web/brand.py
Created brand.py module in oct/pages for implementing objects on Product page and Brand page
Created brand.py module in oct/tests/web for implementing and running test case which verifies ability open brand page from product page.
=> Open brand page test case has been created.

oct/pages/contact_us.py, oct/tests/web/contact_us.py
Created contact_us.py module in oct/pages for implementig objects on the Contact Us page.
Created contact_us.py module in oct/tests/web for implementing and running test case which verifies ablility to send massage with contact us form.
=> Contact Us test case has been created.

oct/pages/affiliate_register.py, oct/tests/web/affiliate_register.py
Created affiliate_register_paypal.py module in oct/pages for implementig objects on the affiliate register page.
Created affiliate_register_paypal.py module in oct/tests/web for implementing and running test case which verifies ablility to register affiliate account.
=> Affiliate register test case has been created.

oct/pages/returns.py, oct/tests/web/returns.py
Created returns.py module in oct/pages for implementing objects on the Returns page.
Created returns.py module in oct/tests/web for implementing and running test case which verifies ability to send request for product return.
=> Returns test case has been created

oct/pages/product_page.py, oct/tests/web/open_prod_img.py
In product_page file added open_product_image function
Added oct/tests/web/open_prod_img.py for run test
In brand page was deleted mistakes
=> Open product image test case was implemented

oct/pages/gift_certificate.py, oct/tests/web/gift_certificate.py
This commit contain creation GiftCertificate class and
Purchasesuccessful class in pages and GiftCertificate in test/web, this class have methods
which search require fields and fill it with valid data, after this
we checking that is new page is opened and confirmation message is
shown.
=> Creating gift certificate page and test

oct/pages/forgot_password.py, oct/tests/web/forgot_password_test.py
This is positive test case for forgot password function. After inputting valid data test should be passed
=> Test case on forgot password function

oct/pages/product_page.py, oct/pages/review.py, oct/tests/web/review.py
Added review.py module in oct/pages for implementing objects on the product
review page.
Added review.py module in oct/tests/web for implementing and running test case
which verifies ability to add review on the product page.
=> Adding review test case has been created.

oct/pages/product_page.py, oct/pages/share.py, oct/tests/web/share.py
Added share.py module in oct/pages for implementig share object on the product
page.
Added share.py module in oct/tests/web for implementing and running test case
which verifies ability to open share popup window on the product page.
=> Share test case has been created.

oct/browsers.py, oct/pages/account.py, oct/pages/affiliate_register.py, oct/pages/contact_us.py, oct/pages/forgot_password.py, oct/pages/gift_certificate.py, oct/pages/login.py, oct/pages/product_page.py, oct/pages/registration.py, oct/pages/returns.py
In modified files has been deleted implicity_wait
In browser.py was added implicity_wait
=> Implicit waiting has been set up when creating a browser instance #17

oct/pages/returns.py, oct/tests/web/returns.py
All possible reasons and conditions were declared within  'Reason', 'Condition' enum.
And this enum has to be used when a reason and condition needs to be set.
#30
=> Test Case: Update "returns" using enumerations #30 has been inplemented

oct/tests/api/login.py, requirements.txt
Login test case was implemented for checking ability login into
user account (with valid credentials) using API.
Opencart website was deployed on remote VM, connection to the site
is not secure. For ability make login with 'https' protocol, was
added parameter 'verify' in thr post method . In this case warning
'InsecureRequestWarning' is shown, for disabling this warning,
'urllib3' library was imported.
In file requirements.txt was added name of 'urllib3' library with
current version. #26
=> Implement login test case via API

oct/pages/product_page.py, oct/tests/web/adding_to_wish_list.py, oct/tests/web/brand.py, oct/tests/web/share.py
Created press_add_to_wish_list method and successful_adding_to_wish_list method in oct/pages/product_page.py
1. press_add_to_wish_list method adds the product to the wish list.
2. successful_adding_to_wish_list method checks that the message about adding product to the wish list is displayed.
Created adding_to_wish_list.py module in oct/tests/web was created for implementation and running the test case.
=> Created the test case of adding the product to the wish list.

oct/tests/web/forgot_password_test.py
In file oct/tests/web/forgot_password_test.py was added new negative test case for forgot password functional
=> Forgot password test cases

docker-compose.yaml, oct/tests/deployment/deploy_app.py, testbed.yaml
Testbed file was modified. Added information about connection to server.
Docker-compose.yaml was added
Deploy_app was created. This file describes a deployment test.
=> Add Deploy_app test #23

oct/tests/web/creating_emails.py, oct/tests/web/registration.py
This method is generating random first part in email address.
First part of email may contain uppercase and lowercase letters in random order.
This method we can use in ragistration cases and other cases if it's need.
This method was created with goal not to rewrite each time the email.
=> In file email_generator.py was added method for creating randon email

oct/tests/api/forgot_passwrd.py
Test cases are checking possibility to send email with a goal of getting confirmation link.
Two test cases with valid and not valid data for positive and negative testing.
=> Api test cases for forgot password functional

suite.py
Missing modules were imported from api package, web package, deployment package to suite.py. Missing modules were added to _api_tests, _web_tests, _deployment_tests in suite.py. #27
=> Modified suite.py module for running all testcases.

oct/pages/brands.py, oct/tests/web/all_brands.py
The page with all brands are added in this commit, and test which check redirecting to the apple brand page from the all brands page are implemented.
=> Brands page and brands_apple test are added

suite.py
File was configured to run tests in next sequence:
1. API test suite
2. WEB test suite
Only if API test suite is passed, will run WEB test suite. It's means
that, if one or more tests from API test suite has failed, WEB test suite
will skipped.
=> Configure execution sequence for WEB and API tests

oct/tests/api/gift_certificate.py
This commit contains API test for the gift_certificate. Creating
GiftCertificate class and using post method from the request library.
=> Implemented API test for gift_certificate

suite.py
In suite was added deployment and destroy tests. Now suite will work
with next sequence:
1. Run deploy test
2. API tests
3. WEB tests
4. Destroy test
It means have some logic:
If deploy test is passed > start run API tests, if they passed >
start run WEB test > and finaly regardless of the result of API & WEB
tests, will run destroy test.
#58
=> Integrate deployments with a job file

README.md, code-assessment.sh, tests/test_emailsGeneration.py
The minimum email length is checked. Local part minimum 2 characters + "@ mailinator.com" (15 characters) = 17 characters.
Check for maximum length (254 characters).
Check if there is a domain name.
Check whether there is a "com."
Check for the number of characters "@".
Check if there is a ". @".
Check if the first character is a letter. #47
=> Create unitests for creating_full_email function.

oct/tests/api/login.py, oct/tests/api/registration.py, oct/tests/web/registration.py, requirements.txt
In this commit implemented issue #25
To run registration test case added randomize of data
with help of module mimesis. Module mimesis randomize next
data in registration test cases:
- first_name
- last_name
- phone
- email
- password
=> Added library mimesis and changed registration files

oct/tests/api/affiliate_register.py, oct/tests/web/affiliate_register.py
Added randomize of data using module memesis
Next data randomized:
-name
-last_name
-email
-company
-website
-phone
-password
=> Added data randomize in affiliate registration tests

.gitignore, oct/tests/deployment/deploy_app.py, oct/tests/deployment/destroy_app.py
For better code readability, a class Running has been added.
This class using in deploy and destroy tests.
=> Added Enum class for deploy test

oct/tests/api/affiliate_register.py, oct/tests/api/contact_us.py, oct/tests/api/gift_certificate.py, oct/tests/api/returns.py, oct/tests/api/review.py
Removed unnecessary variables
Requests moved to assert
Operations performed in the following tests:
1.affiliate_register
2.contact_us
3.returns
4.rewiew
5.gift-certificate
=> Optimized api tests

.flake8, .pydocstyle, code-assessment.sh, oct/pages/account.py, oct/pages/affiliate_register.py, oct/pages/base.py, oct/pages/brand.py, oct/pages/brands.py, oct/pages/contact_us.py, oct/pages/forgot_password.py, oct/pages/gift_certificate.py, oct/pages/login.py, oct/pages/product_page.py, oct/pages/registration.py, oct/pages/returns.py, oct/tests/web/adding_to_cart.py, oct/tests/web/adding_to_wish_list.py, oct/tests/web/affiliate_register.py, oct/tests/web/all_brands.py, oct/tests/web/brand.py, oct/tests/web/contact_us.py, oct/tests/web/forgot_password_test.py, oct/tests/web/gift_certificate.py, oct/tests/web/login.py, oct/tests/web/open_prod_img.py, oct/tests/web/registration.py, oct/tests/web/returns.py, oct/tests/web/review.py, oct/tests/web/share.py, requirements-dev.txt
Due to the fact that the use of "flake8-docstrinds" cause verification errors relate to "pydocstyle",
it makeing the "pydocstyle" check separately from the "flake8" check.
So "pydocstyle" check add to "code-assesment.sh"
Also specify the versions "pydocstyle" and "flake8" add to "requirments-dev.txt" and
"flake8-docstrinds" delete from "requirments-dev.txt"
Since "open" and "load" methods are system methods this methods of the "Page" class renaming
"open" to "loaded" and "load" to "availble".
=> Add pydocstyle check

oct/__main__.py, oct/testbed_rules.py, oct/tests/__init__.py, requirements-dev.txt, requirements.txt, tests/__init__.py
Includes:
- pyATS 19.7 support
- refactoring of testbed validation rules
=> Resolve errors with testbed validation

README.md
This commit update README.md
Delete suite.py from structure
Add:
Directory:
- tests
Files:
- docker-compose.yaml
- Vagrantfile
- testbed.yaml
- requirements-dev.txt
- code-assesment.sh
- __main__.py
=> Update project structure in README.md

README.md
Add section Environment installation and Vagrant installation
replase to Environment installation
In section Vagrant update description after runing
Add liks to Vagrant site and Virtualbox site
=> Add section Environment installation in README.md

README.md
Delete section Deploy and destroy application
Add section docker to Execution
Add link to docker site
=> Add Docker section to README.md
